> Script de la base de datos
```sql
    DROP DATABASE IF EXISTS parcial;

    CREATE DATABASE parcial;

    USE parcial;

    CREATE table categorias_de_carros (
        id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
        categoria VARCHAR1(150) NOT NULL UNIQUE,
        tipo_vehiculo VARCHAR(150) NOT NULL,
        descripción VARCHAR(150) NOT NULL
        
    ); 

    CREATE table autos (
        id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
        marca VARCHAR(150) NOT NULL,
        garantia DATE NOT NULL,
        cilindraje INT NOT NULL,
        FOREIGN KEY (id_categorias_de_carros) REFERENCES categorias_de_carros(id),
        descripciónVARCHAR(150) NOT NULL
    ); 

    CREATE table persona (
        id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
        nombre VARCHAR1(150) NOT NULL UNIQUE,
        apellido VARCHAR(150) NOT NULL,
        telefono INT NOT NULL,
        dirección VARCHAR(150) NOT NULL,
        documento INT NOT NULL
    ); 

    CREATE table Autos_persona  (
        id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
        FOREIGN KEY (id_autos) REFERENCES autos(id),
        FOREIGN KEY (id_persona) REFERENCES persona(id),
        descripción VARCHAR(150) NOT NULL
        
    ); 
```


@startuml BaseDatos

class Categoria_de_comida{
    - int : id
    - String : categoria
    - String : tipo_comida
    - String : descripción
    - float : precio
}

class Facturacion{
    - Categoria_de_comida: precio
    - float : total_reserva
    - float : total_domicilio
    - String : metodo_pago
}

class Reserva{
    - int : id
    - String : nombre
    - String : apellido
    - String : fecha_hora
    - String : cant_personas
    - Categoria_de_comida : id_categorias_de_comidas 
}

class Domicilio{
    - int : id
    - String : nombre
    - String : apellido
    - int : telefono
    - String : dirección
    - int : documento
    - Categoria_de_comida : tipo_comida
    - Categoria_de_comida : total_comida
}

Categoria_de_comida "1" -- "*" Facturacion : tiene
Reserva "1" -- "*" Categoria_de_comida : tiene
Domicilio "1" -- "*" Categoria_de_comida : tiene
Reserva "1" -- "*" Facturacion : tiene
Domicilio "1" -- "*" Facturacion : tiene

@enduml