> Script de la base de datos
```sql
    DROP DATABASE IF EXISTS parcial;

    CREATE DATABASE parcial;

    USE parcial;

    CREATE table categorias_de_carros (
        id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
        categoria VARCHAR1(150) NOT NULL UNIQUE,
        tipo_vehiculo VARCHAR(150) NOT NULL,
        descripción VARCHAR(150) NOT NULL
        
    ); 

    CREATE table autos (
        id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
        marca VARCHAR(150) NOT NULL,
        garantia DATE NOT NULL,
        cilindraje INT NOT NULL,
        FOREIGN KEY (id_categorias_de_carros) REFERENCES categorias_de_carros(id),
        descripciónVARCHAR(150) NOT NULL
    ); 

    CREATE table persona (
        id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
        nombre VARCHAR1(150) NOT NULL UNIQUE,
        apellido VARCHAR(150) NOT NULL,
        telefono INT NOT NULL,
        dirección VARCHAR(150) NOT NULL,
        documento INT NOT NULL
    ); 

    CREATE table Autos_persona  (
        id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
        FOREIGN KEY (id_autos) REFERENCES autos(id),
        FOREIGN KEY (id_persona) REFERENCES persona(id),
        descripción VARCHAR(150) NOT NULL
        
    ); 
```


@startuml BaseDatos

class categorias_de_carros{
    - int : id
    - String : categoria
    - String : tipo_vehiculo
    - String : descripción
}

class autos{
    - int : id
    - String : marca
    - String : garantia
    - String : cilindraje
    - categorias_de_carros : id_categorias_de_carros
    - String : descripción
}

class persona{
    - int : id
    - String : nombre
    - String : apellido
    - int : telefono
    - String : dirección
    - int : documento
}

class autos_persona{
    - int : id
    - autos: id_autos
    - persona : id_persona
    - String : descripción
}

persona "1" -- "*" autos_persona : tiene 
autos "1" -- "*" categorias_de_carros : tiene 
autos "1" -- "*" autos_persona: tienen

@enduml